package org.example.enums;

public enum ConfigJson {
    ANDROID_APP_ACTIVITY, ANDROID_APP_PACKAGE, ANDROID_DEVICE_NAME,
    ANDROID_UDID, ANDROID_SYSTEM_PORT, ANDROID_CHROMEDRIVER_PORT, ANDROID_EMULATOR,
    APPIUM_URL, AVD_LAUNCH_TIMEOUT,
    IOS_DEVICE_NAME, IOS_UDID, IOS_WDA_LOCAL_PORT, IOS_WEBKIT_DEBUG_PROXY_PORT,
    IOS_BUNDLE_ID,
    PLATFORM,
    USERNAME_BROWSERSTACK, ACCESS_KEY_BROWSERSTACK,
    BROWSERSTACK_URL, APP, ANDROID_OS_VERSION,
    ANDROID_PROJECT, ANDROID_BUILD, ANDROID_NAME,
    APP_IOS, IOS_OS_VERSION,
    IOS_PROJECT, IOS_BUILD, IOS_NAME, BROWSERSTACK_URL_IOS,
    LOCAL, BROWSERSTACK_IDLE_TIMEOUT, APPIUM_VERSION,
    IOS_LOCAL, IOS_BROWSERSTACK_IDLE_TIMEOUT, IOS_APPIUM_VERSION
}
